language: node_js
node_js:
  - '8'
  - '6'
  - '4'
before_script:
  - npm install -g gulp
  - gulp lint
after_success: npm run coveralls

# whitelist
branches:
  only:
    - master

notifications:
  email:
    - kempdogg@gmail.com
